theme: jekyll-theme-cayman
title: '<a href="/IR-imaging-of-galaxies-under-light-pollution/" style="color: white">Near IR Imaging of Galaxies Under Light Pollution</a>'
google_analytics: UA-186183409-2
plugins:
 - jekyll-sitemap
